version: '3.7'

services:
  db:
    image: postgres
    restart: always
    container_name: app_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=log_api
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: app_api
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
